from decimal import Decimal

from django.test import TestCase
from django.urls import reverse

from .models import Category, Product


class ProductModelTests(TestCase):
    def setUp(self):
        self.cat = Category.objects.create(name="Audio")

    def test_slug_is_autogenerated(self):
        p = Product.objects.create(
            category=self.cat, name="Cool Headphones", description="d", price=Decimal("10")
        )
        self.assertEqual(p.slug, "cool-headphones")

    def test_slug_is_unique(self):
        p1 = Product.objects.create(
            category=self.cat, name="Same Name", description="d", price=Decimal("10")
        )
        p2 = Product.objects.create(
            category=self.cat, name="Same Name", description="d", price=Decimal("10")
        )
        self.assertNotEqual(p1.slug, p2.slug)

    def test_on_sale_and_discount(self):
        p = Product.objects.create(
            category=self.cat, name="Deal", description="d",
            price=Decimal("80"), compare_at_price=Decimal("100"),
        )
        self.assertTrue(p.on_sale)
        self.assertEqual(p.discount_percent, 20)

    def test_not_on_sale_when_no_compare_price(self):
        p = Product.objects.create(
            category=self.cat, name="Plain", description="d", price=Decimal("80")
        )
        self.assertFalse(p.on_sale)
        self.assertEqual(p.discount_percent, 0)

    def test_display_image_falls_back(self):
        p = Product.objects.create(
            category=self.cat, name="No Image", description="d", price=Decimal("5")
        )
        self.assertIn("picsum", p.display_image)
        p.image_url = "https://example.com/x.jpg"
        self.assertEqual(p.display_image, "https://example.com/x.jpg")


class StoreViewTests(TestCase):
    def setUp(self):
        self.cat = Category.objects.create(name="Audio", slug="audio")
        self.product = Product.objects.create(
            category=self.cat, name="Test Speaker", description="loud",
            price=Decimal("50"), stock=5,
        )

    def test_home_ok(self):
        self.assertEqual(self.client.get(reverse("store:home")).status_code, 200)

    def test_product_list_and_search(self):
        r = self.client.get(reverse("store:product_list"), {"q": "speaker"})
        self.assertContains(r, "Test Speaker")
        r = self.client.get(reverse("store:product_list"), {"q": "nonexistent"})
        self.assertNotContains(r, "Test Speaker")

    def test_category_filter(self):
        r = self.client.get(self.cat.get_absolute_url())
        self.assertContains(r, "Test Speaker")

    def test_product_detail(self):
        r = self.client.get(self.product.get_absolute_url())
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "Test Speaker")
